definitions:
  entity.Translation:
    properties:
      destination:
        example: en
        type: string
      original:
        example: текст для перевода
        type: string
      source:
        example: auto
        type: string
      translation:
        example: text for translation
        type: string
    type: object
  github.com_kuiyonggen_go-clean-template_internal_controller_http_v1.doTranslateRequest:
    properties:
      destination:
        example: en
        type: string
      original:
        example: текст для перевода
        type: string
      source:
        example: auto
        type: string
    required:
    - destination
    - original
    - source
    type: object
  github.com_kuiyonggen_go-clean-template_internal_controller_http_v1.greetingRequest:
    properties:
      name:
        example: alice
        type: string
    required:
    - name
    type: object
  github.com_kuiyonggen_go-clean-template_internal_controller_http_v1.historyResponse:
    properties:
      history:
        items:
          $ref: '#/definitions/entity.Translation'
        type: array
    type: object
  github.com_kuiyonggen_go-clean-template_internal_controller_http_v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
  internal_controller_http_v1.doTranslateRequest:
    properties:
      destination:
        example: en
        type: string
      original:
        example: текст для перевода
        type: string
      source:
        example: auto
        type: string
    required:
    - destination
    - original
    - source
    type: object
  internal_controller_http_v1.greetingRequest:
    properties:
      name:
        example: alice
        type: string
    required:
    - name
    type: object
  internal_controller_http_v1.historyResponse:
    properties:
      history:
        items:
          $ref: '#/definitions/entity.Translation'
        type: array
    type: object
  internal_controller_http_v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
info:
  contact: {}
paths:
  /hello/greeting:
    post:
      consumes:
      - application/json
      description: Greeting
      operationId: greeting
      parameters:
      - description: greeting
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_controller_http_v1.greetingRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controller_http_v1.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_controller_http_v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_controller_http_v1.response'
      summary: Greeting
      tags:
      - hello
  /hello/say:
    get:
      consumes:
      - application/json
      description: Show hello
      operationId: echo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controller_http_v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_controller_http_v1.response'
      summary: Show hello
      tags:
      - hello
  /translation/do-translate:
    post:
      consumes:
      - application/json
      description: Translate a text
      operationId: do-translate
      parameters:
      - description: Set up translation
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_controller_http_v1.doTranslateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Translation'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_controller_http_v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_controller_http_v1.response'
      summary: Translate
      tags:
      - translation
  /translation/history:
    get:
      consumes:
      - application/json
      description: Show all translation history
      operationId: history
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controller_http_v1.historyResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_controller_http_v1.response'
      summary: Show history
      tags:
      - translation
swagger: "2.0"
